//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessDigital.TransactionDataService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class InfoServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortErrorMessageField;
        
        private string techImplementationDetailsField;
        
        private string errCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shortErrorMessage {
            get {
                return this.shortErrorMessageField;
            }
            set {
                this.shortErrorMessageField = value;
                this.RaisePropertyChanged("shortErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string techImplementationDetails {
            get {
                return this.techImplementationDetailsField;
            }
            set {
                this.techImplementationDetailsField = value;
                this.RaisePropertyChanged("techImplementationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class ProcessingStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", ConfigurationName="TransactionDataService.TransactionDataService")]
    public interface TransactionDataService {

        // CODEGEN: Generating message contract since the operation getProcessingStatusTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://ws.digitalpaytech.com/transactionData/getProcessingStatusTypes", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getProcessingStatusTypes", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse getProcessingStatusTypes(DataAccessDigital.TransactionDataService.getProcessingStatusTypes request);

        //// CODEGEN: Generating message contract since the operation getProcessingStatusTypes is neither RPC nor document wrapped.
        //[System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getProcessingStatusTypes", ReplyAction="*")]
        //[System.ServiceModel.FaultContractAttribute(typeof(DataAccess.TransactionDataService.InfoServiceFault), Action="http://ws.digitalpaytech.com/transactionData/getProcessingStatusTypes", Name="InfoServiceFault")]
        //[System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        //DataAccess.TransactionDataService.getProcessingStatusTypesResponse getProcessingStatusTypes(DataAccess.TransactionDataService.getProcessingStatusTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getProcessingStatusTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse> getProcessingStatusTypesAsync(DataAccessDigital.TransactionDataService.getProcessingStatusTypes request);
        
        // CODEGEN: Generating message contract since the operation getPaymentTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getPaymentTypes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getPaymentTypes", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.TransactionDataService.getPaymentTypesResponse getPaymentTypes(DataAccessDigital.TransactionDataService.getPaymentTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getPaymentTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaymentTypesResponse> getPaymentTypesAsync(DataAccessDigital.TransactionDataService.getPaymentTypes request);
        
        // CODEGEN: Generating message contract since the operation getPaystations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getPaystations", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getPaystations", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.TransactionDataService.getPaystationsResponse getPaystations(DataAccessDigital.TransactionDataService.getPaystations request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getPaystations", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaystationsResponse> getPaystationsAsync(DataAccessDigital.TransactionDataService.getPaystations request);
        
        // CODEGEN: Generating message contract since the operation getTransactionTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getTransactionTypes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getTransactionTypes", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.TransactionDataService.getTransactionTypesResponse getTransactionTypes(DataAccessDigital.TransactionDataService.getTransactionTypes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getTransactionTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionTypesResponse> getTransactionTypesAsync(DataAccessDigital.TransactionDataService.getTransactionTypes request);
        
        // CODEGEN: Generating message contract since the operation getTransactionByUpdateDate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getTransactionByPurchasedDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getTransactionByPurchasedDate", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse getTransactionByUpdateDate(DataAccessDigital.TransactionDataService.getTransactionByUpdateDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getTransactionByPurchasedDate", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse> getTransactionByUpdateDateAsync(DataAccessDigital.TransactionDataService.getTransactionByUpdateDate request);
        
        // CODEGEN: Generating message contract since the operation getLocations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getLocations", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.TransactionDataService.InfoServiceFault), Action = "http://ws.digitalpaytech.com/transactionData/getLocations", Name = "InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.TransactionDataService.getLocationsResponse getLocations(DataAccessDigital.TransactionDataService.getLocations request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/transactionData/getLocations", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getLocationsResponse> getLocationsAsync(DataAccessDigital.TransactionDataService.getLocations request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class ProcessingStatusTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessingStatusTypes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.ProcessingStatusTypeRequest ProcessingStatusTypeRequest;
        
        public getProcessingStatusTypes() {
        }
        
        public getProcessingStatusTypes(DataAccessDigital.TransactionDataService.ProcessingStatusTypeRequest ProcessingStatusTypeRequest) {
            this.ProcessingStatusTypeRequest = ProcessingStatusTypeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProcessingStatusTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("processingStatusType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.TransactionDataService.ProcessingStatusType[] ProcessingStatusTypeResponse;
        
        public getProcessingStatusTypesResponse() {
        }
        
        public getProcessingStatusTypesResponse(DataAccessDigital.TransactionDataService.ProcessingStatusType[] ProcessingStatusTypeResponse) {
            this.ProcessingStatusTypeResponse = ProcessingStatusTypeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class PaymentTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private VersionType versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public VersionType version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
                this.RaisePropertyChanged("versionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public enum VersionType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("v1.0")]
        v10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("v1.1")]
        v11,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class PaymentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentTypes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.PaymentTypeRequest PaymentTypeRequest;
        
        public getPaymentTypes() {
        }
        
        public getPaymentTypes(DataAccessDigital.TransactionDataService.PaymentTypeRequest PaymentTypeRequest) {
            this.PaymentTypeRequest = PaymentTypeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("paymentType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.TransactionDataService.PaymentType[] PaymentTypeResponse;
        
        public getPaymentTypesResponse() {
        }
        
        public getPaymentTypesResponse(DataAccessDigital.TransactionDataService.PaymentType[] PaymentTypeResponse) {
            this.PaymentTypeResponse = PaymentTypeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class PaystationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class PaystationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private string paystationNameField;
        
        private int locationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string paystationName {
            get {
                return this.paystationNameField;
            }
            set {
                this.paystationNameField = value;
                this.RaisePropertyChanged("paystationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
                this.RaisePropertyChanged("locationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaystations {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.PaystationRequest PaystationRequest;
        
        public getPaystations() {
        }
        
        public getPaystations(DataAccessDigital.TransactionDataService.PaystationRequest PaystationRequest) {
            this.PaystationRequest = PaystationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaystationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("paystations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.TransactionDataService.PaystationType[] PaystationResponse;
        
        public getPaystationsResponse() {
        }
        
        public getPaystationsResponse(DataAccessDigital.TransactionDataService.PaystationType[] PaystationResponse) {
            this.PaystationResponse = PaystationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class TransactionTypeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class TransactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sbyte id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionTypes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.TransactionTypeRequest TransactionTypeRequest;
        
        public getTransactionTypes() {
        }
        
        public getTransactionTypes(DataAccessDigital.TransactionDataService.TransactionTypeRequest TransactionTypeRequest) {
            this.TransactionTypeRequest = TransactionTypeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transactionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.TransactionDataService.TransactionType[] TransactionTypeResponse;
        
        public getTransactionTypesResponse() {
        }
        
        public getTransactionTypesResponse(DataAccessDigital.TransactionDataService.TransactionType[] TransactionTypeResponse) {
            this.TransactionTypeResponse = TransactionTypeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class TransactionByUpdateDateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.DateTime updateDateFromField;
        
        private System.DateTime updateDateToField;
        
        private VersionType versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime updateDateFrom {
            get {
                return this.updateDateFromField;
            }
            set {
                this.updateDateFromField = value;
                this.RaisePropertyChanged("updateDateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime updateDateTo {
            get {
                return this.updateDateToField;
            }
            set {
                this.updateDateToField = value;
                this.RaisePropertyChanged("updateDateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public VersionType version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified {
            get {
                return this.versionFieldSpecified;
            }
            set {
                this.versionFieldSpecified = value;
                this.RaisePropertyChanged("versionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class TransactionDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private string paystationNameField;
        
        private string settingNameField;
        
        private string paystationTypeField;
        
        private int locationIdField;
        
        private int ticketNumberField;
        
        private string stallNumberField;
        
        private System.DateTime purchasedDateField;
        
        private System.DateTime expirationDateField;
        
        private sbyte paymentTypeField;
        
        private sbyte transactionTypeField;
        
        private string cardTypeField;
        
        private string cardNumberField;
        
        private string cardProcessingAuthorizationNumberField;
        
        private System.DateTime cardProcessingDateField;
        
        private bool cardProcessingDateFieldSpecified;
        
        private string cardProcessingStatusField;
        
        private string cardProcessingReferenceNumberField;
        
        private string cardProcessingMerchantAccountField;
        
        private int cardProcessingRetriesField;
        
        private bool cardProcessingRetriesFieldSpecified;
        
        private string cardProcessingTransactionIdField;
        
        private string couponNumberField;
        
        private int couponDiscountPercentField;
        
        private bool couponDiscountPercentFieldSpecified;
        
        private float couponDiscountDollarField;
        
        private bool couponDiscountDollarFieldSpecified;
        
        private float excessAmountField;
        
        private float refundTicketAmountField;
        
        private float refundChangeIssuedField;
        
        private float chargedAmountField;
        
        private float totalCashAmountField;
        
        private float totalCardAmountField;
        
        private bool totalCardAmountFieldSpecified;
        
        private long rateIdField;
        
        private bool rateIdFieldSpecified;
        
        private string rateNameField;
        
        private float rateValueField;
        
        private bool rateValueFieldSpecified;
        
        private string plateNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string paystationName {
            get {
                return this.paystationNameField;
            }
            set {
                this.paystationNameField = value;
                this.RaisePropertyChanged("paystationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string settingName {
            get {
                return this.settingNameField;
            }
            set {
                this.settingNameField = value;
                this.RaisePropertyChanged("settingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string paystationType {
            get {
                return this.paystationTypeField;
            }
            set {
                this.paystationTypeField = value;
                this.RaisePropertyChanged("paystationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
                this.RaisePropertyChanged("locationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ticketNumber {
            get {
                return this.ticketNumberField;
            }
            set {
                this.ticketNumberField = value;
                this.RaisePropertyChanged("ticketNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string stallNumber {
            get {
                return this.stallNumberField;
            }
            set {
                this.stallNumberField = value;
                this.RaisePropertyChanged("stallNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime purchasedDate {
            get {
                return this.purchasedDateField;
            }
            set {
                this.purchasedDateField = value;
                this.RaisePropertyChanged("purchasedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("expirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public sbyte paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public sbyte transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("transactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("cardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string cardProcessingAuthorizationNumber {
            get {
                return this.cardProcessingAuthorizationNumberField;
            }
            set {
                this.cardProcessingAuthorizationNumberField = value;
                this.RaisePropertyChanged("cardProcessingAuthorizationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime cardProcessingDate {
            get {
                return this.cardProcessingDateField;
            }
            set {
                this.cardProcessingDateField = value;
                this.RaisePropertyChanged("cardProcessingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cardProcessingDateSpecified {
            get {
                return this.cardProcessingDateFieldSpecified;
            }
            set {
                this.cardProcessingDateFieldSpecified = value;
                this.RaisePropertyChanged("cardProcessingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string cardProcessingStatus {
            get {
                return this.cardProcessingStatusField;
            }
            set {
                this.cardProcessingStatusField = value;
                this.RaisePropertyChanged("cardProcessingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string cardProcessingReferenceNumber {
            get {
                return this.cardProcessingReferenceNumberField;
            }
            set {
                this.cardProcessingReferenceNumberField = value;
                this.RaisePropertyChanged("cardProcessingReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string cardProcessingMerchantAccount {
            get {
                return this.cardProcessingMerchantAccountField;
            }
            set {
                this.cardProcessingMerchantAccountField = value;
                this.RaisePropertyChanged("cardProcessingMerchantAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int cardProcessingRetries {
            get {
                return this.cardProcessingRetriesField;
            }
            set {
                this.cardProcessingRetriesField = value;
                this.RaisePropertyChanged("cardProcessingRetries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cardProcessingRetriesSpecified {
            get {
                return this.cardProcessingRetriesFieldSpecified;
            }
            set {
                this.cardProcessingRetriesFieldSpecified = value;
                this.RaisePropertyChanged("cardProcessingRetriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string cardProcessingTransactionId {
            get {
                return this.cardProcessingTransactionIdField;
            }
            set {
                this.cardProcessingTransactionIdField = value;
                this.RaisePropertyChanged("cardProcessingTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string couponNumber {
            get {
                return this.couponNumberField;
            }
            set {
                this.couponNumberField = value;
                this.RaisePropertyChanged("couponNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int couponDiscountPercent {
            get {
                return this.couponDiscountPercentField;
            }
            set {
                this.couponDiscountPercentField = value;
                this.RaisePropertyChanged("couponDiscountPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool couponDiscountPercentSpecified {
            get {
                return this.couponDiscountPercentFieldSpecified;
            }
            set {
                this.couponDiscountPercentFieldSpecified = value;
                this.RaisePropertyChanged("couponDiscountPercentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public float couponDiscountDollar {
            get {
                return this.couponDiscountDollarField;
            }
            set {
                this.couponDiscountDollarField = value;
                this.RaisePropertyChanged("couponDiscountDollar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool couponDiscountDollarSpecified {
            get {
                return this.couponDiscountDollarFieldSpecified;
            }
            set {
                this.couponDiscountDollarFieldSpecified = value;
                this.RaisePropertyChanged("couponDiscountDollarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public float excessAmount {
            get {
                return this.excessAmountField;
            }
            set {
                this.excessAmountField = value;
                this.RaisePropertyChanged("excessAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public float refundTicketAmount {
            get {
                return this.refundTicketAmountField;
            }
            set {
                this.refundTicketAmountField = value;
                this.RaisePropertyChanged("refundTicketAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public float refundChangeIssued {
            get {
                return this.refundChangeIssuedField;
            }
            set {
                this.refundChangeIssuedField = value;
                this.RaisePropertyChanged("refundChangeIssued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public float chargedAmount {
            get {
                return this.chargedAmountField;
            }
            set {
                this.chargedAmountField = value;
                this.RaisePropertyChanged("chargedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public float totalCashAmount {
            get {
                return this.totalCashAmountField;
            }
            set {
                this.totalCashAmountField = value;
                this.RaisePropertyChanged("totalCashAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public float totalCardAmount {
            get {
                return this.totalCardAmountField;
            }
            set {
                this.totalCardAmountField = value;
                this.RaisePropertyChanged("totalCardAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCardAmountSpecified {
            get {
                return this.totalCardAmountFieldSpecified;
            }
            set {
                this.totalCardAmountFieldSpecified = value;
                this.RaisePropertyChanged("totalCardAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public long rateId {
            get {
                return this.rateIdField;
            }
            set {
                this.rateIdField = value;
                this.RaisePropertyChanged("rateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rateIdSpecified {
            get {
                return this.rateIdFieldSpecified;
            }
            set {
                this.rateIdFieldSpecified = value;
                this.RaisePropertyChanged("rateIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string rateName {
            get {
                return this.rateNameField;
            }
            set {
                this.rateNameField = value;
                this.RaisePropertyChanged("rateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public float rateValue {
            get {
                return this.rateValueField;
            }
            set {
                this.rateValueField = value;
                this.RaisePropertyChanged("rateValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rateValueSpecified {
            get {
                return this.rateValueFieldSpecified;
            }
            set {
                this.rateValueFieldSpecified = value;
                this.RaisePropertyChanged("rateValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string plateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
                this.RaisePropertyChanged("plateNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionByUpdateDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.TransactionByUpdateDateRequest TransactionByUpdateDateRequest;
        
        public getTransactionByUpdateDate() {
        }
        
        public getTransactionByUpdateDate(DataAccessDigital.TransactionDataService.TransactionByUpdateDateRequest TransactionByUpdateDateRequest) {
            this.TransactionByUpdateDateRequest = TransactionByUpdateDateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionByUpdateDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transactionDataTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.TransactionDataService.TransactionDataType[] TransactionResponse;
        
        public getTransactionByUpdateDateResponse() {
        }
        
        public getTransactionByUpdateDateResponse(DataAccessDigital.TransactionDataService.TransactionDataType[] TransactionResponse) {
            this.TransactionResponse = TransactionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class LocationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/transactionData")]
    public partial class LocationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int locationIdField;
        
        private string locationNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
                this.RaisePropertyChanged("locationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocations {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        public DataAccessDigital.TransactionDataService.LocationRequest LocationRequest;
        
        public getLocations() {
        }
        
        public getLocations(DataAccessDigital.TransactionDataService.LocationRequest LocationRequest) {
            this.LocationRequest = LocationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/transactionData", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Locations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataAccessDigital.TransactionDataService.LocationType[] LocationResponse;
        
        public getLocationsResponse() {
        }
        
        public getLocationsResponse(DataAccessDigital.TransactionDataService.LocationType[] LocationResponse) {
            this.LocationResponse = LocationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionDataServiceChannel : DataAccessDigital.TransactionDataService.TransactionDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionDataServiceClient : System.ServiceModel.ClientBase<DataAccessDigital.TransactionDataService.TransactionDataService>, DataAccessDigital.TransactionDataService.TransactionDataService
    {
        
        public TransactionDataServiceClient() {
        }
        
        public TransactionDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse DataAccessDigital.TransactionDataService.TransactionDataService.getProcessingStatusTypes(DataAccessDigital.TransactionDataService.getProcessingStatusTypes request)
        {
            return base.Channel.getProcessingStatusTypes(request);
        }

        public DataAccessDigital.TransactionDataService.ProcessingStatusType[] getProcessingStatusTypes(DataAccessDigital.TransactionDataService.ProcessingStatusTypeRequest ProcessingStatusTypeRequest)
        {
            DataAccessDigital.TransactionDataService.getProcessingStatusTypes inValue = new DataAccessDigital.TransactionDataService.getProcessingStatusTypes();
            inValue.ProcessingStatusTypeRequest = ProcessingStatusTypeRequest;
            DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getProcessingStatusTypes(inValue);
            return retVal.ProcessingStatusTypeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getProcessingStatusTypesAsync(DataAccessDigital.TransactionDataService.getProcessingStatusTypes request)
        {
            return base.Channel.getProcessingStatusTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getProcessingStatusTypesResponse> getProcessingStatusTypesAsync(DataAccessDigital.TransactionDataService.ProcessingStatusTypeRequest ProcessingStatusTypeRequest) {
            DataAccessDigital.TransactionDataService.getProcessingStatusTypes inValue = new DataAccessDigital.TransactionDataService.getProcessingStatusTypes();
            inValue.ProcessingStatusTypeRequest = ProcessingStatusTypeRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getProcessingStatusTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getPaymentTypesResponse DataAccessDigital.TransactionDataService.TransactionDataService.getPaymentTypes(DataAccessDigital.TransactionDataService.getPaymentTypes request) {
            return base.Channel.getPaymentTypes(request);
        }
        
        public DataAccessDigital.TransactionDataService.PaymentType[] getPaymentTypes(DataAccessDigital.TransactionDataService.PaymentTypeRequest PaymentTypeRequest) {
            DataAccessDigital.TransactionDataService.getPaymentTypes inValue = new DataAccessDigital.TransactionDataService.getPaymentTypes();
            inValue.PaymentTypeRequest = PaymentTypeRequest;
            DataAccessDigital.TransactionDataService.getPaymentTypesResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getPaymentTypes(inValue);
            return retVal.PaymentTypeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaymentTypesResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getPaymentTypesAsync(DataAccessDigital.TransactionDataService.getPaymentTypes request) {
            return base.Channel.getPaymentTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaymentTypesResponse> getPaymentTypesAsync(DataAccessDigital.TransactionDataService.PaymentTypeRequest PaymentTypeRequest) {
            DataAccessDigital.TransactionDataService.getPaymentTypes inValue = new DataAccessDigital.TransactionDataService.getPaymentTypes();
            inValue.PaymentTypeRequest = PaymentTypeRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getPaymentTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getPaystationsResponse DataAccessDigital.TransactionDataService.TransactionDataService.getPaystations(DataAccessDigital.TransactionDataService.getPaystations request)
        {
            return base.Channel.getPaystations(request);
        }
        
        public DataAccessDigital.TransactionDataService.PaystationType[] getPaystations(DataAccessDigital.TransactionDataService.PaystationRequest PaystationRequest) {
            DataAccessDigital.TransactionDataService.getPaystations inValue = new DataAccessDigital.TransactionDataService.getPaystations();
            inValue.PaystationRequest = PaystationRequest;
            DataAccessDigital.TransactionDataService.getPaystationsResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getPaystations(inValue);
            return retVal.PaystationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaystationsResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getPaystationsAsync(DataAccessDigital.TransactionDataService.getPaystations request) {
            return base.Channel.getPaystationsAsync(request);
        }

        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getPaystationsResponse> getPaystationsAsync(DataAccessDigital.TransactionDataService.PaystationRequest PaystationRequest)
        {
            DataAccessDigital.TransactionDataService.getPaystations inValue = new DataAccessDigital.TransactionDataService.getPaystations();
            inValue.PaystationRequest = PaystationRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getPaystationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getTransactionTypesResponse DataAccessDigital.TransactionDataService.TransactionDataService.getTransactionTypes(DataAccessDigital.TransactionDataService.getTransactionTypes request) {
            return base.Channel.getTransactionTypes(request);
        }
        
        public DataAccessDigital.TransactionDataService.TransactionType[] getTransactionTypes(DataAccessDigital.TransactionDataService.TransactionTypeRequest TransactionTypeRequest) {
            DataAccessDigital.TransactionDataService.getTransactionTypes inValue = new DataAccessDigital.TransactionDataService.getTransactionTypes();
            inValue.TransactionTypeRequest = TransactionTypeRequest;
            DataAccessDigital.TransactionDataService.getTransactionTypesResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getTransactionTypes(inValue);
            return retVal.TransactionTypeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionTypesResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getTransactionTypesAsync(DataAccessDigital.TransactionDataService.getTransactionTypes request) {
            return base.Channel.getTransactionTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionTypesResponse> getTransactionTypesAsync(DataAccessDigital.TransactionDataService.TransactionTypeRequest TransactionTypeRequest) {
            DataAccessDigital.TransactionDataService.getTransactionTypes inValue = new DataAccessDigital.TransactionDataService.getTransactionTypes();
            inValue.TransactionTypeRequest = TransactionTypeRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getTransactionTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse DataAccessDigital.TransactionDataService.TransactionDataService.getTransactionByUpdateDate(DataAccessDigital.TransactionDataService.getTransactionByUpdateDate request) {
            return base.Channel.getTransactionByUpdateDate(request);
        }
        
        public DataAccessDigital.TransactionDataService.TransactionDataType[] getTransactionByUpdateDate(DataAccessDigital.TransactionDataService.TransactionByUpdateDateRequest TransactionByUpdateDateRequest) {
            DataAccessDigital.TransactionDataService.getTransactionByUpdateDate inValue = new DataAccessDigital.TransactionDataService.getTransactionByUpdateDate();
            inValue.TransactionByUpdateDateRequest = TransactionByUpdateDateRequest;
            DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getTransactionByUpdateDate(inValue);
            return retVal.TransactionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getTransactionByUpdateDateAsync(DataAccessDigital.TransactionDataService.getTransactionByUpdateDate request) {
            return base.Channel.getTransactionByUpdateDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getTransactionByUpdateDateResponse> getTransactionByUpdateDateAsync(DataAccessDigital.TransactionDataService.TransactionByUpdateDateRequest TransactionByUpdateDateRequest) {
            DataAccessDigital.TransactionDataService.getTransactionByUpdateDate inValue = new DataAccessDigital.TransactionDataService.getTransactionByUpdateDate();
            inValue.TransactionByUpdateDateRequest = TransactionByUpdateDateRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getTransactionByUpdateDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.TransactionDataService.getLocationsResponse DataAccessDigital.TransactionDataService.TransactionDataService.getLocations(DataAccessDigital.TransactionDataService.getLocations request)
        {
            return base.Channel.getLocations(request);
        }
        
        public DataAccessDigital.TransactionDataService.LocationType[] getLocations(DataAccessDigital.TransactionDataService.LocationRequest LocationRequest) {
            DataAccessDigital.TransactionDataService.getLocations inValue = new DataAccessDigital.TransactionDataService.getLocations();
            inValue.LocationRequest = LocationRequest;
            DataAccessDigital.TransactionDataService.getLocationsResponse retVal = ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getLocations(inValue);
            return retVal.LocationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getLocationsResponse> DataAccessDigital.TransactionDataService.TransactionDataService.getLocationsAsync(DataAccessDigital.TransactionDataService.getLocations request) {
            return base.Channel.getLocationsAsync(request);
        }

        public System.Threading.Tasks.Task<DataAccessDigital.TransactionDataService.getLocationsResponse> getLocationsAsync(DataAccessDigital.TransactionDataService.LocationRequest LocationRequest)
        {
            DataAccessDigital.TransactionDataService.getLocations inValue = new DataAccessDigital.TransactionDataService.getLocations();
            inValue.LocationRequest = LocationRequest;
            return ((DataAccessDigital.TransactionDataService.TransactionDataService)(this)).getLocationsAsync(inValue);
        }
    }
}
