//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessDigital.StallInfoService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class InfoServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortErrorMessageField;
        
        private string techImplementationDetailsField;
        
        private string errCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shortErrorMessage {
            get {
                return this.shortErrorMessageField;
            }
            set {
                this.shortErrorMessageField = value;
                this.RaisePropertyChanged("shortErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string techImplementationDetails {
            get {
                return this.techImplementationDetailsField;
            }
            set {
                this.techImplementationDetailsField = value;
                this.RaisePropertyChanged("techImplementationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class SettingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string settingNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string settingName {
            get {
                return this.settingNameField;
            }
            set {
                this.settingNameField = value;
                this.RaisePropertyChanged("settingName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", ConfigurationName="StallInfoService.StallInfoService")]
    public interface StallInfoService {
        
        // CODEGEN: Generating message contract since the operation getSettings is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getSettings", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getSettings", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getSettingsResponse getSettings(DataAccessDigital.StallInfoService.getSettings request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getSettingsResponse> getSettingsAsync(DataAccessDigital.StallInfoService.getSettings request);
        
        // CODEGEN: Generating message contract since the operation getRegions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getRegions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getRegions", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getRegionsResponse getRegions(DataAccessDigital.StallInfoService.getRegions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getRegions", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getRegionsResponse> getRegionsAsync(DataAccessDigital.StallInfoService.getRegions request);
        
        // CODEGEN: Generating message contract since the operation getStallInfoByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getStallInfoByGroupResponse getStallInfoByGroup(DataAccessDigital.StallInfoService.getStallInfoByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByGroupResponse> getStallInfoByGroupAsync(DataAccessDigital.StallInfoService.getStallInfoByGroup request);
        
        // CODEGEN: Generating message contract since the operation getStallInfoByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getStallInfoByRegionResponse getStallInfoByRegion(DataAccessDigital.StallInfoService.getStallInfoByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByRegionResponse> getStallInfoByRegionAsync(DataAccessDigital.StallInfoService.getStallInfoByRegion request);
        
        // CODEGEN: Generating message contract since the operation getGroups is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getGroups", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getGroups", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getGroupsResponse getGroups(DataAccessDigital.StallInfoService.getGroups request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getGroupsResponse> getGroupsAsync(DataAccessDigital.StallInfoService.getGroups request);
        
        // CODEGEN: Generating message contract since the operation getStallInfoBySetting is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoBySetting", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoBySetting", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getStallInfoBySettingResponse getStallInfoBySetting(DataAccessDigital.StallInfoService.getStallInfoBySetting request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfoBySetting", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoBySettingResponse> getStallInfoBySettingAsync(DataAccessDigital.StallInfoService.getStallInfoBySetting request);
        
        // CODEGEN: Generating message contract since the operation getStallInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.StallInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/stallInfo/getStallInfo", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.StallInfoService.getStallInfoResponse getStallInfo(DataAccessDigital.StallInfoService.getStallInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/stallInfo/getStallInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoResponse> getStallInfoAsync(DataAccessDigital.StallInfoService.getStallInfo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class SettingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSettings {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.SettingRequest SettingRequest;
        
        public getSettings() {
        }
        
        public getSettings(DataAccessDigital.StallInfoService.SettingRequest SettingRequest) {
            this.SettingRequest = SettingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("settings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.SettingType[] SettingResponse;
        
        public getSettingsResponse() {
        }
        
        public getSettingsResponse(DataAccessDigital.StallInfoService.SettingType[] SettingResponse) {
            this.SettingResponse = SettingResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class RegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class RegionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string regionNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.RegionRequest RegionRequest;
        
        public getRegions() {
        }
        
        public getRegions(DataAccessDigital.StallInfoService.RegionRequest RegionRequest) {
            this.RegionRequest = RegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("regions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.RegionType[] RegionResponse;
        
        public getRegionsResponse() {
        }
        
        public getRegionsResponse(DataAccessDigital.StallInfoService.RegionType[] RegionResponse) {
            this.RegionResponse = RegionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class StallInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private int stallfromField;
        
        private int stalltoField;
        
        private Bystatus stallstatusField;
        
        private System.DateTime datetimeStampField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stallfrom {
            get {
                return this.stallfromField;
            }
            set {
                this.stallfromField = value;
                this.RaisePropertyChanged("stallfrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stallto {
            get {
                return this.stalltoField;
            }
            set {
                this.stalltoField = value;
                this.RaisePropertyChanged("stallto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Bystatus stallstatus {
            get {
                return this.stallstatusField;
            }
            set {
                this.stallstatusField = value;
                this.RaisePropertyChanged("stallstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datetimeStamp {
            get {
                return this.datetimeStampField;
            }
            set {
                this.datetimeStampField = value;
                this.RaisePropertyChanged("datetimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public enum Bystatus {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Valid,
        
        /// <remarks/>
        Expired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class StallInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime expiryDateField;
        
        private System.DateTime purchaseDateField;
        
        private string stallNumberField;
        
        private string settingField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime purchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
                this.RaisePropertyChanged("purchaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stallNumber {
            get {
                return this.stallNumberField;
            }
            set {
                this.stallNumberField = value;
                this.RaisePropertyChanged("stallNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
                this.RaisePropertyChanged("setting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.StallInfoByGroupRequest StallInfoByGroupRequest;
        
        public getStallInfoByGroup() {
        }
        
        public getStallInfoByGroup(DataAccessDigital.StallInfoService.StallInfoByGroupRequest StallInfoByGroupRequest) {
            this.StallInfoByGroupRequest = StallInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stallInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse;
        
        public getStallInfoByGroupResponse() {
        }
        
        public getStallInfoByGroupResponse(DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse) {
            this.StallInfoResponse = StallInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class StallInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private int stallfromField;
        
        private int stalltoField;
        
        private Bystatus stallstatusField;
        
        private System.DateTime datetimeStampField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stallfrom {
            get {
                return this.stallfromField;
            }
            set {
                this.stallfromField = value;
                this.RaisePropertyChanged("stallfrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stallto {
            get {
                return this.stalltoField;
            }
            set {
                this.stalltoField = value;
                this.RaisePropertyChanged("stallto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Bystatus stallstatus {
            get {
                return this.stallstatusField;
            }
            set {
                this.stallstatusField = value;
                this.RaisePropertyChanged("stallstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datetimeStamp {
            get {
                return this.datetimeStampField;
            }
            set {
                this.datetimeStampField = value;
                this.RaisePropertyChanged("datetimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.StallInfoByRegionRequest StallInfoByRegionRequest;
        
        public getStallInfoByRegion() {
        }
        
        public getStallInfoByRegion(DataAccessDigital.StallInfoService.StallInfoByRegionRequest StallInfoByRegionRequest) {
            this.StallInfoByRegionRequest = StallInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stallInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse;
        
        public getStallInfoByRegionResponse() {
        }
        
        public getStallInfoByRegionResponse(DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse) {
            this.StallInfoResponse = StallInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class GroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class GroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroups {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.GroupRequest GroupRequest;
        
        public getGroups() {
        }
        
        public getGroups(DataAccessDigital.StallInfoService.GroupRequest GroupRequest) {
            this.GroupRequest = GroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.GroupType[] GroupResponse;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(DataAccessDigital.StallInfoService.GroupType[] GroupResponse) {
            this.GroupResponse = GroupResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class StallInfoBySettingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string settingField;
        
        private int stallfromField;
        
        private int stalltoField;
        
        private Bystatus stallstatusField;
        
        private System.DateTime datetimeStampField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
                this.RaisePropertyChanged("setting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stallfrom {
            get {
                return this.stallfromField;
            }
            set {
                this.stallfromField = value;
                this.RaisePropertyChanged("stallfrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stallto {
            get {
                return this.stalltoField;
            }
            set {
                this.stalltoField = value;
                this.RaisePropertyChanged("stallto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Bystatus stallstatus {
            get {
                return this.stallstatusField;
            }
            set {
                this.stallstatusField = value;
                this.RaisePropertyChanged("stallstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime datetimeStamp {
            get {
                return this.datetimeStampField;
            }
            set {
                this.datetimeStampField = value;
                this.RaisePropertyChanged("datetimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoBySetting {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.StallInfoBySettingRequest StallInfoBySettingRequest;
        
        public getStallInfoBySetting() {
        }
        
        public getStallInfoBySetting(DataAccessDigital.StallInfoService.StallInfoBySettingRequest StallInfoBySettingRequest) {
            this.StallInfoBySettingRequest = StallInfoBySettingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoBySettingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stallInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse;
        
        public getStallInfoBySettingResponse() {
        }
        
        public getStallInfoBySettingResponse(DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse) {
            this.StallInfoResponse = StallInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/stallInfo")]
    public partial class StallInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private int stallfromField;
        
        private int stalltoField;
        
        private Bystatus stallstatusField;
        
        private System.DateTime datetimeStampField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int stallfrom {
            get {
                return this.stallfromField;
            }
            set {
                this.stallfromField = value;
                this.RaisePropertyChanged("stallfrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stallto {
            get {
                return this.stalltoField;
            }
            set {
                this.stalltoField = value;
                this.RaisePropertyChanged("stallto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Bystatus stallstatus {
            get {
                return this.stallstatusField;
            }
            set {
                this.stallstatusField = value;
                this.RaisePropertyChanged("stallstatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime datetimeStamp {
            get {
                return this.datetimeStampField;
            }
            set {
                this.datetimeStampField = value;
                this.RaisePropertyChanged("datetimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        public DataAccessDigital.StallInfoService.StallInfoRequest StallInfoRequest;
        
        public getStallInfo() {
        }
        
        public getStallInfo(DataAccessDigital.StallInfoService.StallInfoRequest StallInfoRequest) {
            this.StallInfoRequest = StallInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStallInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/stallInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stallInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse;
        
        public getStallInfoResponse() {
        }
        
        public getStallInfoResponse(DataAccessDigital.StallInfoService.StallInfoType[] StallInfoResponse) {
            this.StallInfoResponse = StallInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StallInfoServiceChannel : DataAccessDigital.StallInfoService.StallInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StallInfoServiceClient : System.ServiceModel.ClientBase<DataAccessDigital.StallInfoService.StallInfoService>, DataAccessDigital.StallInfoService.StallInfoService {
        
        public StallInfoServiceClient() {
        }
        
        public StallInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StallInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StallInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StallInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getSettingsResponse DataAccessDigital.StallInfoService.StallInfoService.getSettings(DataAccessDigital.StallInfoService.getSettings request) {
            return base.Channel.getSettings(request);
        }
        
        public DataAccessDigital.StallInfoService.SettingType[] getSettings(DataAccessDigital.StallInfoService.SettingRequest SettingRequest) {
            DataAccessDigital.StallInfoService.getSettings inValue = new DataAccessDigital.StallInfoService.getSettings();
            inValue.SettingRequest = SettingRequest;
            DataAccessDigital.StallInfoService.getSettingsResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getSettings(inValue);
            return retVal.SettingResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getSettingsResponse> DataAccessDigital.StallInfoService.StallInfoService.getSettingsAsync(DataAccessDigital.StallInfoService.getSettings request) {
            return base.Channel.getSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getSettingsResponse> getSettingsAsync(DataAccessDigital.StallInfoService.SettingRequest SettingRequest) {
            DataAccessDigital.StallInfoService.getSettings inValue = new DataAccessDigital.StallInfoService.getSettings();
            inValue.SettingRequest = SettingRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getRegionsResponse DataAccessDigital.StallInfoService.StallInfoService.getRegions(DataAccessDigital.StallInfoService.getRegions request) {
            return base.Channel.getRegions(request);
        }
        
        public DataAccessDigital.StallInfoService.RegionType[] getRegions(DataAccessDigital.StallInfoService.RegionRequest RegionRequest) {
            DataAccessDigital.StallInfoService.getRegions inValue = new DataAccessDigital.StallInfoService.getRegions();
            inValue.RegionRequest = RegionRequest;
            DataAccessDigital.StallInfoService.getRegionsResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getRegions(inValue);
            return retVal.RegionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getRegionsResponse> DataAccessDigital.StallInfoService.StallInfoService.getRegionsAsync(DataAccessDigital.StallInfoService.getRegions request) {
            return base.Channel.getRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getRegionsResponse> getRegionsAsync(DataAccessDigital.StallInfoService.RegionRequest RegionRequest) {
            DataAccessDigital.StallInfoService.getRegions inValue = new DataAccessDigital.StallInfoService.getRegions();
            inValue.RegionRequest = RegionRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getRegionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getStallInfoByGroupResponse DataAccessDigital.StallInfoService.StallInfoService.getStallInfoByGroup(DataAccessDigital.StallInfoService.getStallInfoByGroup request) {
            return base.Channel.getStallInfoByGroup(request);
        }
        
        public DataAccessDigital.StallInfoService.StallInfoType[] getStallInfoByGroup(DataAccessDigital.StallInfoService.StallInfoByGroupRequest StallInfoByGroupRequest) {
            DataAccessDigital.StallInfoService.getStallInfoByGroup inValue = new DataAccessDigital.StallInfoService.getStallInfoByGroup();
            inValue.StallInfoByGroupRequest = StallInfoByGroupRequest;
            DataAccessDigital.StallInfoService.getStallInfoByGroupResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoByGroup(inValue);
            return retVal.StallInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByGroupResponse> DataAccessDigital.StallInfoService.StallInfoService.getStallInfoByGroupAsync(DataAccessDigital.StallInfoService.getStallInfoByGroup request) {
            return base.Channel.getStallInfoByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByGroupResponse> getStallInfoByGroupAsync(DataAccessDigital.StallInfoService.StallInfoByGroupRequest StallInfoByGroupRequest) {
            DataAccessDigital.StallInfoService.getStallInfoByGroup inValue = new DataAccessDigital.StallInfoService.getStallInfoByGroup();
            inValue.StallInfoByGroupRequest = StallInfoByGroupRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getStallInfoByRegionResponse DataAccessDigital.StallInfoService.StallInfoService.getStallInfoByRegion(DataAccessDigital.StallInfoService.getStallInfoByRegion request) {
            return base.Channel.getStallInfoByRegion(request);
        }
        
        public DataAccessDigital.StallInfoService.StallInfoType[] getStallInfoByRegion(DataAccessDigital.StallInfoService.StallInfoByRegionRequest StallInfoByRegionRequest) {
            DataAccessDigital.StallInfoService.getStallInfoByRegion inValue = new DataAccessDigital.StallInfoService.getStallInfoByRegion();
            inValue.StallInfoByRegionRequest = StallInfoByRegionRequest;
            DataAccessDigital.StallInfoService.getStallInfoByRegionResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoByRegion(inValue);
            return retVal.StallInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByRegionResponse> DataAccessDigital.StallInfoService.StallInfoService.getStallInfoByRegionAsync(DataAccessDigital.StallInfoService.getStallInfoByRegion request) {
            return base.Channel.getStallInfoByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoByRegionResponse> getStallInfoByRegionAsync(DataAccessDigital.StallInfoService.StallInfoByRegionRequest StallInfoByRegionRequest) {
            DataAccessDigital.StallInfoService.getStallInfoByRegion inValue = new DataAccessDigital.StallInfoService.getStallInfoByRegion();
            inValue.StallInfoByRegionRequest = StallInfoByRegionRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getGroupsResponse DataAccessDigital.StallInfoService.StallInfoService.getGroups(DataAccessDigital.StallInfoService.getGroups request) {
            return base.Channel.getGroups(request);
        }
        
        public DataAccessDigital.StallInfoService.GroupType[] getGroups(DataAccessDigital.StallInfoService.GroupRequest GroupRequest) {
            DataAccessDigital.StallInfoService.getGroups inValue = new DataAccessDigital.StallInfoService.getGroups();
            inValue.GroupRequest = GroupRequest;
            DataAccessDigital.StallInfoService.getGroupsResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getGroups(inValue);
            return retVal.GroupResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getGroupsResponse> DataAccessDigital.StallInfoService.StallInfoService.getGroupsAsync(DataAccessDigital.StallInfoService.getGroups request) {
            return base.Channel.getGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getGroupsResponse> getGroupsAsync(DataAccessDigital.StallInfoService.GroupRequest GroupRequest) {
            DataAccessDigital.StallInfoService.getGroups inValue = new DataAccessDigital.StallInfoService.getGroups();
            inValue.GroupRequest = GroupRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getStallInfoBySettingResponse DataAccessDigital.StallInfoService.StallInfoService.getStallInfoBySetting(DataAccessDigital.StallInfoService.getStallInfoBySetting request) {
            return base.Channel.getStallInfoBySetting(request);
        }
        
        public DataAccessDigital.StallInfoService.StallInfoType[] getStallInfoBySetting(DataAccessDigital.StallInfoService.StallInfoBySettingRequest StallInfoBySettingRequest) {
            DataAccessDigital.StallInfoService.getStallInfoBySetting inValue = new DataAccessDigital.StallInfoService.getStallInfoBySetting();
            inValue.StallInfoBySettingRequest = StallInfoBySettingRequest;
            DataAccessDigital.StallInfoService.getStallInfoBySettingResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoBySetting(inValue);
            return retVal.StallInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoBySettingResponse> DataAccessDigital.StallInfoService.StallInfoService.getStallInfoBySettingAsync(DataAccessDigital.StallInfoService.getStallInfoBySetting request) {
            return base.Channel.getStallInfoBySettingAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoBySettingResponse> getStallInfoBySettingAsync(DataAccessDigital.StallInfoService.StallInfoBySettingRequest StallInfoBySettingRequest) {
            DataAccessDigital.StallInfoService.getStallInfoBySetting inValue = new DataAccessDigital.StallInfoService.getStallInfoBySetting();
            inValue.StallInfoBySettingRequest = StallInfoBySettingRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoBySettingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.StallInfoService.getStallInfoResponse DataAccessDigital.StallInfoService.StallInfoService.getStallInfo(DataAccessDigital.StallInfoService.getStallInfo request) {
            return base.Channel.getStallInfo(request);
        }
        
        public DataAccessDigital.StallInfoService.StallInfoType[] getStallInfo(DataAccessDigital.StallInfoService.StallInfoRequest StallInfoRequest) {
            DataAccessDigital.StallInfoService.getStallInfo inValue = new DataAccessDigital.StallInfoService.getStallInfo();
            inValue.StallInfoRequest = StallInfoRequest;
            DataAccessDigital.StallInfoService.getStallInfoResponse retVal = ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfo(inValue);
            return retVal.StallInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoResponse> DataAccessDigital.StallInfoService.StallInfoService.getStallInfoAsync(DataAccessDigital.StallInfoService.getStallInfo request) {
            return base.Channel.getStallInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.StallInfoService.getStallInfoResponse> getStallInfoAsync(DataAccessDigital.StallInfoService.StallInfoRequest StallInfoRequest) {
            DataAccessDigital.StallInfoService.getStallInfo inValue = new DataAccessDigital.StallInfoService.getStallInfo();
            inValue.StallInfoRequest = StallInfoRequest;
            return ((DataAccessDigital.StallInfoService.StallInfoService)(this)).getStallInfoAsync(inValue);
        }
    }
}
