//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessDigital.PlateInfoService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class InfoServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortErrorMessageField;
        
        private string techImplementationDetailsField;
        
        private string errCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shortErrorMessage {
            get {
                return this.shortErrorMessageField;
            }
            set {
                this.shortErrorMessageField = value;
                this.RaisePropertyChanged("shortErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string techImplementationDetails {
            get {
                return this.techImplementationDetailsField;
            }
            set {
                this.techImplementationDetailsField = value;
                this.RaisePropertyChanged("techImplementationDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime expiryDateField;
        
        private System.DateTime purchasedDateField;
        
        private string plateNumberField;
        
        private string regionNameField;
        
        private StatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime purchasedDate {
            get {
                return this.purchasedDateField;
            }
            set {
                this.purchasedDateField = value;
                this.RaisePropertyChanged("purchasedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string plateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
                this.RaisePropertyChanged("plateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public enum StatusType {
        
        /// <remarks/>
        Valid,
        
        /// <remarks/>
        Expired,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", ConfigurationName="PlateInfoService.PlateInfoService")]
    public interface PlateInfoService {
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse getUpdatedValidPlatesByGroup(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse> getUpdatedValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getValidPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse getValidPlatesByGroup(DataAccessDigital.PlateInfoService.getValidPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse> getValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getValidPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse getUpdatedValidPlates(DataAccessDigital.PlateInfoService.getUpdatedValidPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse> getUpdatedValidPlatesAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlates request);
        
        // CODEGEN: Generating message contract since the operation getPlateInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getPlateInfoResponse getPlateInfo(DataAccessDigital.PlateInfoService.getPlateInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getPlateInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getPlateInfoResponse> getPlateInfoAsync(DataAccessDigital.PlateInfoService.getPlateInfo request);
        
        // CODEGEN: Generating message contract since the operation getValidPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse getValidPlatesByRegion(DataAccessDigital.PlateInfoService.getValidPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse> getValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getValidPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getGroups is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getGroups", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getGroups", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getGroupsResponse getGroups(DataAccessDigital.PlateInfoService.getGroups request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getGroupsResponse> getGroupsAsync(DataAccessDigital.PlateInfoService.getGroups request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlatesByGroup is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse getExpiredPlatesByGroup(DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse> getExpiredPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse getExpiredPlatesByRegion(DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse> getExpiredPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getRegions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getRegions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getRegions", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getRegionsResponse getRegions(DataAccessDigital.PlateInfoService.getRegions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getRegions", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getRegionsResponse> getRegionsAsync(DataAccessDigital.PlateInfoService.getRegions request);
        
        // CODEGEN: Generating message contract since the operation getValidPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getValidPlatesResponse getValidPlates(DataAccessDigital.PlateInfoService.getValidPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getValidPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesResponse> getValidPlatesAsync(DataAccessDigital.PlateInfoService.getValidPlates request);
        
        // CODEGEN: Generating message contract since the operation getUpdatedValidPlatesByRegion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse getUpdatedValidPlatesByRegion(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getUpdatedValidPlatesByRegion", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse> getUpdatedValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion request);
        
        // CODEGEN: Generating message contract since the operation getExpiredPlates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataAccessDigital.PlateInfoService.InfoServiceFault), Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", Name="InfoServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesResponse getExpiredPlates(DataAccessDigital.PlateInfoService.getExpiredPlates request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.digitalpaytech.com/plateInfo/getExpiredPlates", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesResponse> getExpiredPlatesAsync(DataAccessDigital.PlateInfoService.getExpiredPlates request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest;
        
        public getUpdatedValidPlatesByGroup() {
        }
        
        public getUpdatedValidPlatesByGroup(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            this.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesByGroupResponse() {
        }
        
        public getUpdatedValidPlatesByGroupResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.PlateInfoByGroupRequest PlateInfoByGroupRequest;
        
        public getValidPlatesByGroup() {
        }
        
        public getValidPlatesByGroup(DataAccessDigital.PlateInfoService.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            this.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesByGroupResponse() {
        }
        
        public getValidPlatesByGroupResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.UpdatedPlateInfoRequest UpdatedPlateInfoRequest;
        
        public getUpdatedValidPlates() {
        }
        
        public getUpdatedValidPlates(DataAccessDigital.PlateInfoService.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            this.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesResponse() {
        }
        
        public getUpdatedValidPlatesResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByPlateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string plateNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string plateNumber {
            get {
                return this.plateNumberField;
            }
            set {
                this.plateNumberField = value;
                this.RaisePropertyChanged("plateNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByPlateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PlateInfoType plateInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PlateInfoType plateInfo {
            get {
                return this.plateInfoField;
            }
            set {
                this.plateInfoField = value;
                this.RaisePropertyChanged("plateInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlateInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.PlateInfoByPlateRequest PlateInfoByPlateRequest;
        
        public getPlateInfo() {
        }
        
        public getPlateInfo(DataAccessDigital.PlateInfoService.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            this.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlateInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.PlateInfoByPlateResponse PlateInfoByPlateResponse;
        
        public getPlateInfoResponse() {
        }
        
        public getPlateInfoResponse(DataAccessDigital.PlateInfoService.PlateInfoByPlateResponse PlateInfoByPlateResponse) {
            this.PlateInfoByPlateResponse = PlateInfoByPlateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.PlateInfoByRegionRequest PlateInfoByRegionRequest;
        
        public getValidPlatesByRegion() {
        }
        
        public getValidPlatesByRegion(DataAccessDigital.PlateInfoService.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            this.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesByRegionResponse() {
        }
        
        public getValidPlatesByRegionResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class GroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class GroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroups {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.GroupRequest GroupRequest;
        
        public getGroups() {
        }
        
        public getGroups(DataAccessDigital.PlateInfoService.GroupRequest GroupRequest) {
            this.GroupRequest = GroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("groups", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.GroupType[] GroupResponse;
        
        public getGroupsResponse() {
        }
        
        public getGroupsResponse(DataAccessDigital.PlateInfoService.GroupType[] GroupResponse) {
            this.GroupResponse = GroupResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoByGroupRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string groupNameField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByGroup {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest;
        
        public getExpiredPlatesByGroup() {
        }
        
        public getExpiredPlatesByGroup(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            this.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesByGroupResponse() {
        }
        
        public getExpiredPlatesByGroupResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest;
        
        public getExpiredPlatesByRegion() {
        }
        
        public getExpiredPlatesByRegion(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            this.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesByRegionResponse() {
        }
        
        public getExpiredPlatesByRegionResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class RegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class RegionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string regionNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string regionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
                this.RaisePropertyChanged("regionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegions {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.RegionRequest RegionRequest;
        
        public getRegions() {
        }
        
        public getRegions(DataAccessDigital.PlateInfoService.RegionRequest RegionRequest) {
            this.RegionRequest = RegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("regions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.RegionType[] RegionResponse;
        
        public getRegionsResponse() {
        }
        
        public getRegionsResponse(DataAccessDigital.PlateInfoService.RegionType[] RegionResponse) {
            this.RegionResponse = RegionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class PlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.PlateInfoRequest PlateInfoRequest;
        
        public getValidPlates() {
        }
        
        public getValidPlates(DataAccessDigital.PlateInfoService.PlateInfoRequest PlateInfoRequest) {
            this.PlateInfoRequest = PlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getValidPlatesResponse() {
        }
        
        public getValidPlatesResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class UpdatedPlateInfoByRegionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string regionField;
        
        private System.DateTime lastCallDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastCallDate {
            get {
                return this.lastCallDateField;
            }
            set {
                this.lastCallDateField = value;
                this.RaisePropertyChanged("lastCallDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByRegion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest;
        
        public getUpdatedValidPlatesByRegion() {
        }
        
        public getUpdatedValidPlatesByRegion(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            this.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUpdatedValidPlatesByRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getUpdatedValidPlatesByRegionResponse() {
        }
        
        public getUpdatedValidPlatesByRegionResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.digitalpaytech.com/plateInfo")]
    public partial class ExpiredPlateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private int gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
                this.RaisePropertyChanged("gracePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
                this.RaisePropertyChanged("gracePeriodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlates {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        public DataAccessDigital.PlateInfoService.ExpiredPlateInfoRequest ExpiredPlateInfoRequest;
        
        public getExpiredPlates() {
        }
        
        public getExpiredPlates(DataAccessDigital.PlateInfoService.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            this.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getExpiredPlatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.digitalpaytech.com/plateInfo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("plateInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse;
        
        public getExpiredPlatesResponse() {
        }
        
        public getExpiredPlatesResponse(DataAccessDigital.PlateInfoService.PlateInfoType[] PlateInfoResponse) {
            this.PlateInfoResponse = PlateInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlateInfoServiceChannel : DataAccessDigital.PlateInfoService.PlateInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlateInfoServiceClient : System.ServiceModel.ClientBase<DataAccessDigital.PlateInfoService.PlateInfoService>, DataAccessDigital.PlateInfoService.PlateInfoService {
        
        public PlateInfoServiceClient() {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlateInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlateInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlatesByGroup(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup request) {
            return base.Channel.getUpdatedValidPlatesByGroup(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getUpdatedValidPlatesByGroup(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup();
            inValue.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup request) {
            return base.Channel.getUpdatedValidPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroupResponse> getUpdatedValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByGroupRequest UpdatedPlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByGroup();
            inValue.UpdatedPlateInfoByGroupRequest = UpdatedPlateInfoByGroupRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlatesByGroup(DataAccessDigital.PlateInfoService.getValidPlatesByGroup request) {
            return base.Channel.getValidPlatesByGroup(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getValidPlatesByGroup(DataAccessDigital.PlateInfoService.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getValidPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getValidPlatesByGroup();
            inValue.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
            DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getValidPlatesByGroup request) {
            return base.Channel.getValidPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByGroupResponse> getValidPlatesByGroupAsync(DataAccessDigital.PlateInfoService.PlateInfoByGroupRequest PlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getValidPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getValidPlatesByGroup();
            inValue.PlateInfoByGroupRequest = PlateInfoByGroupRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlates(DataAccessDigital.PlateInfoService.getUpdatedValidPlates request) {
            return base.Channel.getUpdatedValidPlates(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getUpdatedValidPlates(DataAccessDigital.PlateInfoService.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlates inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlates();
            inValue.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlatesAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlates request) {
            return base.Channel.getUpdatedValidPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesResponse> getUpdatedValidPlatesAsync(DataAccessDigital.PlateInfoService.UpdatedPlateInfoRequest UpdatedPlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlates inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlates();
            inValue.UpdatedPlateInfoRequest = UpdatedPlateInfoRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getPlateInfoResponse DataAccessDigital.PlateInfoService.PlateInfoService.getPlateInfo(DataAccessDigital.PlateInfoService.getPlateInfo request) {
            return base.Channel.getPlateInfo(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoByPlateResponse getPlateInfo(DataAccessDigital.PlateInfoService.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            DataAccessDigital.PlateInfoService.getPlateInfo inValue = new DataAccessDigital.PlateInfoService.getPlateInfo();
            inValue.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
            DataAccessDigital.PlateInfoService.getPlateInfoResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getPlateInfo(inValue);
            return retVal.PlateInfoByPlateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getPlateInfoResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getPlateInfoAsync(DataAccessDigital.PlateInfoService.getPlateInfo request) {
            return base.Channel.getPlateInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getPlateInfoResponse> getPlateInfoAsync(DataAccessDigital.PlateInfoService.PlateInfoByPlateRequest PlateInfoByPlateRequest) {
            DataAccessDigital.PlateInfoService.getPlateInfo inValue = new DataAccessDigital.PlateInfoService.getPlateInfo();
            inValue.PlateInfoByPlateRequest = PlateInfoByPlateRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getPlateInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlatesByRegion(DataAccessDigital.PlateInfoService.getValidPlatesByRegion request) {
            return base.Channel.getValidPlatesByRegion(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getValidPlatesByRegion(DataAccessDigital.PlateInfoService.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getValidPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getValidPlatesByRegion();
            inValue.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
            DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getValidPlatesByRegion request) {
            return base.Channel.getValidPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesByRegionResponse> getValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.PlateInfoByRegionRequest PlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getValidPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getValidPlatesByRegion();
            inValue.PlateInfoByRegionRequest = PlateInfoByRegionRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getGroupsResponse DataAccessDigital.PlateInfoService.PlateInfoService.getGroups(DataAccessDigital.PlateInfoService.getGroups request) {
            return base.Channel.getGroups(request);
        }
        
        public DataAccessDigital.PlateInfoService.GroupType[] getGroups(DataAccessDigital.PlateInfoService.GroupRequest GroupRequest) {
            DataAccessDigital.PlateInfoService.getGroups inValue = new DataAccessDigital.PlateInfoService.getGroups();
            inValue.GroupRequest = GroupRequest;
            DataAccessDigital.PlateInfoService.getGroupsResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getGroups(inValue);
            return retVal.GroupResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getGroupsResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getGroupsAsync(DataAccessDigital.PlateInfoService.getGroups request) {
            return base.Channel.getGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getGroupsResponse> getGroupsAsync(DataAccessDigital.PlateInfoService.GroupRequest GroupRequest) {
            DataAccessDigital.PlateInfoService.getGroups inValue = new DataAccessDigital.PlateInfoService.getGroups();
            inValue.GroupRequest = GroupRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlatesByGroup(DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup request) {
            return base.Channel.getExpiredPlatesByGroup(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getExpiredPlatesByGroup(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup();
            inValue.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
            DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlatesByGroup(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlatesByGroupAsync(DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup request) {
            return base.Channel.getExpiredPlatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByGroupResponse> getExpiredPlatesByGroupAsync(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByGroupRequest ExpiredPlateInfoByGroupRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup inValue = new DataAccessDigital.PlateInfoService.getExpiredPlatesByGroup();
            inValue.ExpiredPlateInfoByGroupRequest = ExpiredPlateInfoByGroupRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlatesByRegion(DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion request) {
            return base.Channel.getExpiredPlatesByRegion(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getExpiredPlatesByRegion(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion();
            inValue.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
            DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion request) {
            return base.Channel.getExpiredPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesByRegionResponse> getExpiredPlatesByRegionAsync(DataAccessDigital.PlateInfoService.ExpiredPlateInfoByRegionRequest ExpiredPlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getExpiredPlatesByRegion();
            inValue.ExpiredPlateInfoByRegionRequest = ExpiredPlateInfoByRegionRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getRegionsResponse DataAccessDigital.PlateInfoService.PlateInfoService.getRegions(DataAccessDigital.PlateInfoService.getRegions request) {
            return base.Channel.getRegions(request);
        }
        
        public DataAccessDigital.PlateInfoService.RegionType[] getRegions(DataAccessDigital.PlateInfoService.RegionRequest RegionRequest) {
            DataAccessDigital.PlateInfoService.getRegions inValue = new DataAccessDigital.PlateInfoService.getRegions();
            inValue.RegionRequest = RegionRequest;
            DataAccessDigital.PlateInfoService.getRegionsResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getRegions(inValue);
            return retVal.RegionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getRegionsResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getRegionsAsync(DataAccessDigital.PlateInfoService.getRegions request) {
            return base.Channel.getRegionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getRegionsResponse> getRegionsAsync(DataAccessDigital.PlateInfoService.RegionRequest RegionRequest) {
            DataAccessDigital.PlateInfoService.getRegions inValue = new DataAccessDigital.PlateInfoService.getRegions();
            inValue.RegionRequest = RegionRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getRegionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getValidPlatesResponse DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlates(DataAccessDigital.PlateInfoService.getValidPlates request) {
            return base.Channel.getValidPlates(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getValidPlates(DataAccessDigital.PlateInfoService.PlateInfoRequest PlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getValidPlates inValue = new DataAccessDigital.PlateInfoService.getValidPlates();
            inValue.PlateInfoRequest = PlateInfoRequest;
            DataAccessDigital.PlateInfoService.getValidPlatesResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getValidPlatesAsync(DataAccessDigital.PlateInfoService.getValidPlates request) {
            return base.Channel.getValidPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getValidPlatesResponse> getValidPlatesAsync(DataAccessDigital.PlateInfoService.PlateInfoRequest PlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getValidPlates inValue = new DataAccessDigital.PlateInfoService.getValidPlates();
            inValue.PlateInfoRequest = PlateInfoRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getValidPlatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlatesByRegion(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion request) {
            return base.Channel.getUpdatedValidPlatesByRegion(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getUpdatedValidPlatesByRegion(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion();
            inValue.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlatesByRegion(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getUpdatedValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion request) {
            return base.Channel.getUpdatedValidPlatesByRegionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegionResponse> getUpdatedValidPlatesByRegionAsync(DataAccessDigital.PlateInfoService.UpdatedPlateInfoByRegionRequest UpdatedPlateInfoByRegionRequest) {
            DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion inValue = new DataAccessDigital.PlateInfoService.getUpdatedValidPlatesByRegion();
            inValue.UpdatedPlateInfoByRegionRequest = UpdatedPlateInfoByRegionRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getUpdatedValidPlatesByRegionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessDigital.PlateInfoService.getExpiredPlatesResponse DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlates(DataAccessDigital.PlateInfoService.getExpiredPlates request) {
            return base.Channel.getExpiredPlates(request);
        }
        
        public DataAccessDigital.PlateInfoService.PlateInfoType[] getExpiredPlates(DataAccessDigital.PlateInfoService.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlates inValue = new DataAccessDigital.PlateInfoService.getExpiredPlates();
            inValue.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
            DataAccessDigital.PlateInfoService.getExpiredPlatesResponse retVal = ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlates(inValue);
            return retVal.PlateInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesResponse> DataAccessDigital.PlateInfoService.PlateInfoService.getExpiredPlatesAsync(DataAccessDigital.PlateInfoService.getExpiredPlates request) {
            return base.Channel.getExpiredPlatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessDigital.PlateInfoService.getExpiredPlatesResponse> getExpiredPlatesAsync(DataAccessDigital.PlateInfoService.ExpiredPlateInfoRequest ExpiredPlateInfoRequest) {
            DataAccessDigital.PlateInfoService.getExpiredPlates inValue = new DataAccessDigital.PlateInfoService.getExpiredPlates();
            inValue.ExpiredPlateInfoRequest = ExpiredPlateInfoRequest;
            return ((DataAccessDigital.PlateInfoService.PlateInfoService)(this)).getExpiredPlatesAsync(inValue);
        }
    }
}
